const Homeproducts =
[
    {
        id: 1,
        name: 'Software Development',
        price: '150',
        images: 'images/p1.jpg',
        cat: 'getting_into_tech',
        type: 'technology',
    },
    {
        id: 2,
        name: 'Data-Entry',
        price: '200',
        images: 'images/p2.jpg',
        cat: 'getting_into_tech',
        type: 'technology',
    },
    {
        id: 3,
        name: 'Everything on Cybersecurity',
        price: '152',
        images: 'images/p1.jpg',
        cat: 'getting_into_tech',
        type: 'technology',
    },
    {
        id: 4,
        name: 'Introduction to Html',
        price: '145',
        images: 'images/p2.jpg',
        cat: 'getting_into_tech',
        type: 'technology',
    },
    {
        id: 5,
        name: 'Simple Snacks',
        price: '99',
        images: 'images/p1.jpg',
        cat: 'vocational_tips',
        type: 'vocational',
    },
    {
        id: 6,
        name: 'Barbing guide',
        price: '59',
        images: 'images/p2.jpg',
        cat: 'vocational_tips',
        type: 'vocational',
    },
    {
        id: 7,
        name: 'Braiding Pro',
        price: '956',
        images: 'images/p1.jpg',
        cat: 'vocational_tips',
        type: 'vocational',
    },
    {
        id: 8,
        name: 'The Writers guide',
        price: '389',
        images: 'images/p2.jpg',
        cat: 'soft_skills',
        type: 'vocational',
    },
     {
        id: 9,
        name: 'Speak Right',
        price: '67',
        images: 'images/p6.jpg',
        cat: 'communication',
        type: 'softskills',
    },
    {
         id: 9,
         name: 'Time Management',
         price: '76',
         images: 'images/p7.jpg',
         cat: 'time-management',
         type: 'softskills',
     },
    {
         id: 10,
         name: 'Critical Thinking',
         price: '87',
         images: 'images/p8.jpg',
         cat: 'critical-thinking',
         type: 'softskills',
    },
    {
         id: 11,
         name: 'Creativity',
         price: '807',
         images: 'images/p1.jpg',
         cat: 'creativity',
         type: 'softskills',
    },
]
export default Homeproducts